out_dir: results
dataset:
  format: Tfg-nx
  name: ws
  task: node
  task_type: classification
  transductive: False
  split: [0.8, 0.2]
  augment_feature: ['node_identity']
  augment_feature_dims: [10]
  augment_feature_repr: original
  augment_label: node_clustering_coefficient
  augment_label_dims: 10
  transform: none
train:
  batch_size: 128
  eval_period: 10
  ckpt_period: 1000
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 128
  layer_type: Tfg-idgcnfast
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: add
  normalize_adj: False
  l2norm: True
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100
  
  
  
  
  


#dataset.augment_feature feature [[],['node_identity']]
#dataset.augment_label label ['node_clustering_coefficient']
#gnn.layers_pre_mp l_pre [1]
#gnn.layers_mp l_mp [2]
#gnn.layers_post_mp l_post [1]
#gnn.layer_type layer ['gatconv']
#optim.max_epoch epoch [1000]