out_dir: results
dataset:
  format: Tfg-PyG
  name: Cora
  task: node
  task_type: classification
  transductive: True
  split: [0.8, 0.2]

  augment_feature: ['node_identity']
  augment_feature_dims: [10]
  augment_feature_repr: original
  transform: none
train:
  batch_size: 128
  eval_period: 10
  ckpt_period: 1000
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 128
  layer_type: Tfg-gcnconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: add
  normalize_adj: False
  l2norm: True
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100
  
  
  
  
  

